language: ruby
rvm:
  - 2.6.3

install: bundle install
script: jekyll build && htmlproofer ./_site

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler